#!/bin/bash

merge() {
for file in *.gitignore
do
	case $file in
		Eclipse.gitignore);;
		FlexBuilder.gitignore);;
		*)
			type=${file/.gitignore}
    		echo
    		echo '########################################'
    		echo '#' $type
    		echo '########################################'
    		echo
    		cat $file
    		echo
	esac
done
}

#merge >> GITIGNORE
merge
